# -*- coding: utf-8 -*-
"""cvpractical1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QG3bOMFxpvrKaQV70d-KTdIa0D4VS6WQ
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

"""# New Section"""

from google.colab.patches import cv2_imshow
img=cv2.imread("/content/img.jpg")

from google.colab import drive
drive.mount('/content/drive')

img.shape
(4723,3975,3)

resize=np.resize(img,(4072,3096,3))

cv2_imshow(resize)

img.dtype

from google.colab.patches import cv2_imshow
crop=img[500:4723,1300:3975]
cv2_imshow(crop)

img[500,500]

gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_image)