# -*- coding: utf-8 -*-
"""cvpractical2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnz0CdR1MaLgrRXpsgCqAFSs3u1uk3jD
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
img=cv2.imread("/content/img.jpg")
img=cv2.imread('/image.jpg',cv2.IMREAD_GRAYSCALE)
plt.imshow(img,cmap='gray')
plt.show()

def add_salt_probability(image, probability = 0.3):
  noisy = image.copy()
  random = np.random.rand(*image.shape)

  noisy[random < probability/2 ] = 0
  noisy[random > 1 - probability/2] = 255

  return noisy

probability = 0.75



noisy_image = add_salt_probability(img,probability)
plt.imshow(noisy_image,cmap='gray')
plt.show()