# -*- coding: utf-8 -*-
"""cvpractical3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTn0hzBJXPHvKk4fWWTRL14Tgi64u8c3
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("image.jpg", 0)

def add_salt_probability(image, probability = 0.3):
      noisy = image.copy()
      random = np.random.rand(*image.shape)

      noisy[random < probability/2 ] = 0
      noisy[random > 1 - probability/2] = 255

      return noisy
probability = 0.75
noisy_image = add_salt_probability(img,probability)

def median_filter(noisy_image, k=3,s=1):
        h, w = noisy_image.shape
        pad = k // 2
        padded = np.pad(noisy_image, pad, mode='reflect')
        o_h = int(((h - k + (2 * pad)) / s) + 1)
        o_w = int(((w - k + (2 * pad)) / s) + 1)
        output = np.zeros([o_h, o_w], dtype=noisy_image.dtype)

        for i in range(o_h):
            for j in range(o_w):
                window = padded[
                    i * s : i * s + k,
                    j * s : j * s + k]
                output[i, j] = np.median(window)
        return output

def mean_filter(noisy_image, k,s=1):
        h, w = noisy_image.shape
        pad = k // 2
        padded = np.pad(noisy_image, pad, mode='reflect')
        o_h = int(((h - k + (2 * pad)) / s) + 1)
        o_w = int(((w - k + (2 * pad)) / s) + 1)
        output_m = np.zeros([o_h, o_w], dtype=noisy_image.dtype)
        for i in range(o_h):
            for j in range(o_w):

                window = padded[ i*s : i*s + k,
                                j*s : j*s + k]
                output_m[i, j] = np.mean(window)
        return output_m
mean_filtered_noisy_image = mean_filter(noisy_image, k=3)
median_filtered_noisy_image = median_filter(noisy_image, k=3)
plt.figure(figsize=(15, 5))

plt.subplot(1, 4, 1)
plt.imshow(img, cmap='gray')
plt.title("Original image")

plt.subplot(1, 4, 2)
plt.imshow(noisy_image, cmap='gray')
plt.title("Noisy image")

plt.subplot(1, 4, 3)
plt.imshow(mean_filtered_noisy_image, cmap='gray')
plt.title("Mean Filter")

plt.subplot(1, 4, 4)
plt.imshow(median_filtered_noisy_image, cmap='gray')
plt.title("Median Filter")
plt.show()

median_filtered_noisy_image1 = median_filter(noisy_image, s=3)
median_filtered_noisy_image2 = median_filter(noisy_image, s=5)
median_filtered_noisy_image3 = median_filter(noisy_image, s=7)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(median_filtered_noisy_image1, cmap='gray')
plt.title("Median Filter s=3")

plt.subplot(1, 3, 2)
plt.imshow(median_filtered_noisy_image2, cmap='gray')
plt.title("Median Filter s=5")

plt.subplot(1, 3, 3)
plt.imshow(median_filtered_noisy_image3, cmap='gray')
plt.title("Median Filter s=7")

plt.show()
median_filtered_noisy_image1 = median_filter(noisy_image, k=5)
median_filtered_noisy_image2 = median_filter(noisy_image, k=7)
median_filtered_noisy_image3 = median_filter(noisy_image, k=9)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(median_filtered_noisy_image1, cmap='gray')
plt.title("Median filter k=5")

plt.subplot(1, 3, 2)
plt.imshow(median_filtered_noisy_image2, cmap='gray')
plt.title("Median filter k=7")

plt.subplot(1, 3, 3)
plt.imshow(median_filtered_noisy_image3, cmap='gray')
plt.title("Median filter k=9")

plt.show()
mean_filtered_noisy_image1 = mean_filter(noisy_image, s=3)
mean_filtered_noisy_image2 = mean_filter(noisy_image, s=5)
mean_filtered_noisy_image3 = mean_filter(noisy_image, s=7)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(mean_filtered_noisy_image1, cmap='gray')
plt.title("Mean Filter s=3")

plt.subplot(1, 3, 2)
plt.imshow(mean_filtered_noisy_image2, cmap='gray')
plt.title("Mean Filter s=5")

plt.subplot(1, 3, 3)
plt.imshow(mean_filtered_noisy_image3, cmap='gray')
plt.title("Mean Filter s=7")

plt.show()

mean_filtered_noisy_image1 = mean_filter(noisy_image, k=5)
mean_filtered_noisy_image2 = mean_filter(noisy_image, k=7)
mean_filtered_noisy_image3 = mean_filter(noisy_image, k=9)

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(mean_filtered_noisy_image1, cmap='gray')
plt.title("Mean Filter k=5")

plt.subplot(1, 3, 2)
plt.imshow(mean_filtered_noisy_image2, cmap='gray')
plt.title("Mean Filter k=7")

plt.subplot(1, 3, 3)
plt.imshow(mean_filtered_noisy_image3, cmap='gray')
plt.title("Mean Filter k=9")

plt.show()